@startuml
state "сервер-диспетчер BackgroundDispatcher" as CurrentSite #pink {
state "Start This Server" as ProgramCS #red

state Monitor
state RedisKeyEventsProvider #red
state EventKeyFrom #yellow
state EventСafeKey #yellow
state EventKeyUpdate #yellow
state EventKeyTest #yellow

RedisKeyEventsProvider -down[#darkred,dashed]-> EventKeyFrom
RedisKeyEventsProvider -down[#darkred,dashed]-> EventСafeKey
RedisKeyEventsProvider -right[#darkred,dashed]-> EventKeyUpdate
RedisKeyEventsProvider -right[#darkred,dashed]-> EventKeyTest

ProgramCS -down[#blue,bold]-> Monitor
Monitor -[#blue,bold]-> SubscribingPlan
SubscribingPlan -[#blue,bold]-> SubscribeOnEventFrom
SubscribingPlan -[#blue,bold]-> SubscribeOnEventСafeKey
SubscribingPlan -[#blue,bold]-> SubscribeOnEventUpdateKey
SubscribingPlan -[#blue,bold]-> SubscribeOnEventKeyTest

EventKeyFrom -down[#darkred,dashed]-> EventFromOccured
EventСafeKey -down[#darkred,dashed]-> EventEventСafeOccured
EventKeyUpdate -[#darkred,dashed]-> EventEventUpdateOccured
EventKeyTest -[#darkred,dashed]-> EventEventTestOccured

state "OnKeysEventsSubscribeService" as SubscribeService #lightblue {

state SubscribeOnEventFrom #lightgreen {
    state EventFromOccured #coral{
        state EventCounterOccurred
    }
}
state SubscribeOnEventСafeKey #lightgreen {
    state EventEventСafeOccured #coral{
        state EventCounterOccurred1
    }
}
state SubscribeOnEventUpdateKey #lightgreen {
    state EventEventUpdateOccured #coral{
        state EventCounterOccurred3
    }
}
state SubscribeOnEventKeyTest #lightgreen {
    state EventEventTestOccured #coral{
        state EventCounterOccurred4
    }
}


SubscribeOnEventFrom -[#green]-> ConstantInitializer
CheckKeyConstantsUpdate -[#green]-> isExistUpdatedConstants

isExistUpdatedConstants -[#green]-> ConstantInitializer : [true]
isExistUpdatedConstants -[#green]-> isKeyFrontGivesTaskStillExist : [false]

isExistEventKeyFrontGivesTask -[#red]-> _subscribeEnabled : [false]

tasksPackageGuidField -[#red]-> _subscribeEnabled : [null]
tasksPackageGuidField -[#red]-> guidOfTasksPackage : [not null]
guidOfTasksPackage --> TasksBatchProcessingService


}
@enduml
