@startuml
state "сервер фоновых задач BackgroundTasksQueue" as CurrentSite #pink {
state "Start This Server" as ProgramCS #red
state QueuedHostedService
state RedisKeyEventsProvider #red
state EventKeyRun #yellow
state EventKeyUpdate #yellow
RedisKeyEventsProvider -down[#darkred,dashed]-> EventKeyRun
RedisKeyEventsProvider -right[#darkred,dashed]-> EventKeyUpdate
ProgramCS -down[#blue,bold]-> QueuedHostedService
QueuedHostedService -[#blue,bold]-> SubscribeOnEventRun
EventKeyRun -down[#darkred,dashed]-> EventRunOccured
EventKeyUpdate -[#darkred,dashed]-> EventPackageCompletedtOccured

state "класс подписки на ключи OnKeysEventsSubscribeService" as SubscribeService #lightblue {

state SubscribeOnEventRun #lightgreen {
    state EventRunOccured #coral{
        state _subscribeEnabled
    }
}
        state CheckKeyFrontGivesTask #lightgreen {
EventRunOccured  --> CheckKeyFrontGivesTask
_subscribeEnabled -up-> EventRunOccured
CheckKeyFrontGivesTask -[#green]-> CheckKeyConstantsUpdate
state isExistEventKeyFrontGivesTask <<choice>>
isKeyFrontGivesTaskStillExist --> isExistEventKeyFrontGivesTask
state isExistUpdatedConstants <<choice>>
    }  

SubscribeOnEventRun -[#green]-> ConstantInitializer
CheckKeyConstantsUpdate -[#green]-> isExistUpdatedConstants

isExistUpdatedConstants -[#green]-> ConstantInitializer : [true]
isExistUpdatedConstants -[#green]-> isKeyFrontGivesTaskStillExist : [false]

state FreshTaskPackageHasAppeared #lightgreen{
state checkTasksPackageGuidField
state returnGuidTasksPackage
state guidOfTasksPackage
state tasksPackageGuidField <<choice>>
    FreshTaskPackageHasAppeared --> checkTasksPackageGuidField
    returnGuidTasksPackage --> tasksPackageGuidField
isExistEventKeyFrontGivesTask -[#red]-> FreshTaskPackageHasAppeared : [true]
}

isExistEventKeyFrontGivesTask -[#red]-> _subscribeEnabled : [false]

state SubscribeOnEventPackageCompleted #lightgreen {
    state EventPackageCompletedtOccured #coral {
state _flagToBlockEventCompleted
_flagToBlockEventCompleted --> CheckKeyFrontGivesTask

    }
}
}
state SettingConstantsService #lightgray {
    ConstantInitializer --> DeliveryOfUpdatedConstants
DeliveryOfUpdatedConstants -down[#darkgreen]-> SubscribeOnEventRun
DeliveryOfUpdatedConstants -down[#darkgreen]-> isKeyFrontGivesTaskStillExist
}

tasksPackageGuidField -[#red]-> _subscribeEnabled : [null]
tasksPackageGuidField -[#red]-> guidOfTasksPackage : [not null]
guidOfTasksPackage --> TasksBatchProcessingService


state TasksBatchProcessingService #lightgray {   
}


state TasksPackageCaptureService #lightgray {
    state AttemptToCaptureTasksPackage
    checkTasksPackageGuidField --> AttemptToCaptureTasksPackage
}

    AttemptToCaptureTasksPackage --> returnGuidTasksPackage

}
@enduml
